name: depipe
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - aioeasywebdav=2.4.0
  - aiohttp=3.7.4
  - amply=0.1.4
  - appdirs=1.4.4
  - async-timeout=3.0.1
  - atk-1.0=2.36.0
  - attmap=0.13.0
  - attrs=21.2.0
  - autopep8=1.5.7
  - azure-common=1.1.27
  - azure-core=1.14.0
  - azure-storage-blob=12.8.1
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bcrypt=3.2.0
  - bedtools=2.30.0
  - binutils_impl_linux-64=2.35.1
  - binutils_linux-64=2.35
  - bioconductor-annotate=1.68.0
  - bioconductor-annotationdbi=1.52.0
  - bioconductor-biobase=2.50.0
  - bioconductor-biocfilecache=1.14.0
  - bioconductor-biocgenerics=0.36.0
  - bioconductor-biocparallel=1.24.1
  - bioconductor-biomart=2.46.3
  - bioconductor-biostrings=2.58.0
  - bioconductor-chipseeker=1.26.2
  - bioconductor-delayedarray=0.16.3
  - bioconductor-deseq2=1.30.1
  - bioconductor-do.db=2.9
  - bioconductor-dose=3.16.0
  - bioconductor-enrichplot=1.10.2
  - bioconductor-fgsea=1.16.0
  - bioconductor-genefilter=1.72.1
  - bioconductor-geneplotter=1.68.0
  - bioconductor-genomeinfodb=1.26.4
  - bioconductor-genomeinfodbdata=1.2.4
  - bioconductor-genomicalignments=1.26.0
  - bioconductor-genomicfeatures=1.42.2
  - bioconductor-genomicranges=1.42.0
  - bioconductor-go.db=3.12.1
  - bioconductor-gosemsim=2.16.1
  - bioconductor-iranges=2.24.1
  - bioconductor-matrixgenerics=1.2.1
  - bioconductor-org.hs.eg.db=3.12.0
  - bioconductor-qvalue=2.22.0
  - bioconductor-rhtslib=1.22.0
  - bioconductor-rsamtools=2.6.0
  - bioconductor-rtracklayer=1.50.0
  - bioconductor-s4vectors=0.28.1
  - bioconductor-summarizedexperiment=1.20.0
  - bioconductor-txdb.hsapiens.ucsc.hg19.knowngene=3.2.2
  - bioconductor-xvector=0.30.0
  - bioconductor-zlibbioc=1.36.0
  - blinker=1.4
  - boto=2.49.0
  - boto3=1.17.78
  - botocore=1.20.78
  - brotlipy=0.7.0
  - bwa=0.7.17
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.12.5
  - cachetools=4.2.2
  - cairo=1.16.0
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=4.0.0
  - coincbc=2.10.5
  - configargparse=1.4.1
  - connection_pool=0.0.3
  - cryptography=3.4.7
  - curl=7.76.1
  - datrie=0.8.2
  - decorator=4.4.2
  - docutils=0.17.1
  - dropbox=10.10.0
  - expat=2.3.0
  - fastp=0.20.1
  - fftw=3.3.9
  - filechunkio=1.8
  - filelock=3.0.12
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.10.4
  - fribidi=1.0.10
  - ftputil=5.0.1
  - gcc_impl_linux-64=9.3.0
  - gcc_linux-64=9.3.0
  - gdk-pixbuf=2.42.6
  - gettext=0.21.0
  - gfortran_impl_linux-64=9.3.0
  - gfortran_linux-64=9.3.0
  - ghostscript=9.54.0
  - giflib=5.2.1
  - gitdb=4.0.7
  - gitpython=3.1.17
  - gmp=6.2.1
  - google-api-core=1.26.3
  - google-api-python-client=2.5.0
  - google-auth=1.30.0
  - google-auth-httplib2=0.1.0
  - google-cloud-core=1.6.0
  - google-cloud-storage=1.38.0
  - google-crc32c=1.1.2
  - google-resumable-media=1.3.0
  - googleapis-common-protos=1.53.0
  - graphite2=1.3.14
  - graphviz=2.47.1
  - gsl=2.6
  - gtk2=2.24.33
  - gts=0.7.6
  - gxx_impl_linux-64=9.3.0
  - gxx_linux-64=9.3.0
  - harfbuzz=2.8.1
  - htslib=1.12
  - httplib2=0.19.1
  - icu=68.1
  - idna=2.10
  - imagemagick=7.0.11_13
  - importlib-metadata=4.0.1
  - iniconfig=1.1.1
  - ipython_genutils=0.2.0
  - isodate=0.6.0
  - jbig=2.1
  - jinja2=3.0.1
  - jmespath=0.10.0
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter_core=4.7.1
  - kernel-headers_linux-64=2.6.32
  - krb5=1.19.1
  - ld_impl_linux-64=2.35.1
  - lerc=2.2.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcrc32c=1.1.1
  - libcurl=7.76.1
  - libdeflate=1.7
  - libedit=3.1.20210216
  - libev=4.33
  - libffi=3.3
  - libgcc-devel_linux-64=9.3.0
  - libgcc-ng=9.3.0
  - libgd=2.3.2
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libglib=2.68.2
  - libgomp=9.3.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm10=10.0.1
  - libnghttp2=1.43.0
  - libopenblas=0.3.15
  - libpng=1.6.37
  - libprotobuf=3.17.0
  - librsvg=2.50.5
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libstdcxx-devel_linux-64=9.3.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.3.0
  - libtool=2.4.6
  - libuuid=2.32.1
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxml2=2.9.12
  - lineedit=0.1.6
  - llvmlite=0.36.0
  - logmuse=0.2.6
  - lz4-c=1.9.3
  - macs2=2.2.7.1
  - make=4.3
  - markupsafe=2.0.1
  - more-itertools=8.8.0
  - msrest=0.6.21
  - multidict=5.1.0
  - mysql-connector-c=6.1.11
  - nbformat=5.1.3
  - ncurses=6.2
  - networkx=2.5.1
  - numba=0.53.1
  - numpy=1.20.3
  - oauth2client=4.1.3
  - oauthlib=3.1.0
  - openjpeg=2.4.0
  - openssl=1.1.1k
  - packaging=20.9
  - pandas=1.2.4
  - pango=1.48.5
  - paramiko=2.7.2
  - pcre=8.44
  - pcre2=10.36
  - peppy=0.31.1
  - perl=5.32.0
  - pip=21.1.2
  - pixman=0.40.0
  - pkg-config=0.29.2
  - pluggy=0.13.1
  - prettytable=2.1.0
  - protobuf=3.17.0
  - psutil=5.8.0
  - pulp=2.4
  - py=1.10.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycodestyle=2.7.0
  - pycparser=2.20
  - pygments=2.9.0
  - pygraphviz=1.7
  - pyjwt=2.1.0
  - pynacl=1.4.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pysam=0.16.0.1
  - pysftp=0.2.9
  - pysocks=1.7.1
  - pytest=6.2.4
  - python=3.9.5
  - python-dateutil=2.8.1
  - python-irodsclient=0.9.0
  - python_abi=3.9
  - pytz=2021.1
  - pyyaml=5.4.1
  - qnorm=0.7.0
  - r=4.0
  - r-askpass=1.1
  - r-assertthat=0.2.1
  - r-backports=1.2.1
  - r-base=4.0.5
  - r-base64enc=0.1_3
  - r-bh=1.75.0_0
  - r-biocmanager=1.30.15
  - r-bit=4.0.4
  - r-bit64=4.0.5
  - r-bitops=1.0_7
  - r-blob=1.2.1
  - r-boot=1.3_28
  - r-brew=1.0_6
  - r-brio=1.1.2
  - r-cachem=1.0.5
  - r-callr=3.7.0
  - r-catools=1.18.2
  - r-class=7.3_19
  - r-cli=2.5.0
  - r-cluster=2.1.2
  - r-codetools=0.2_18
  - r-collections=0.3.5
  - r-colorspace=2.0_1
  - r-commonmark=1.7
  - r-cowplot=1.1.1
  - r-crayon=1.4.1
  - r-curl=4.3.1
  - r-cyclocomp=1.1.0
  - r-data.table=1.14.0
  - r-dbi=1.1.1
  - r-dbplyr=2.1.1
  - r-desc=1.3.0
  - r-diffobj=0.3.4
  - r-digest=0.6.27
  - r-dplyr=1.0.6
  - r-ellipsis=0.3.2
  - r-evaluate=0.14
  - r-fansi=0.4.2
  - r-farver=2.1.0
  - r-fastmap=1.1.0
  - r-fastmatch=1.1_0
  - r-foreign=0.8_81
  - r-formatr=1.9
  - r-fs=1.5.0
  - r-futile.logger=1.4.3
  - r-futile.options=1.0.1
  - r-generics=0.1.0
  - r-ggforce=0.3.3
  - r-ggplot2=3.3.3
  - r-ggraph=2.0.5
  - r-ggrepel=0.9.1
  - r-glue=1.4.2
  - r-gplots=3.1.1
  - r-graphlayouts=0.7.1
  - r-gridextra=2.3
  - r-gtable=0.3.0
  - r-gtools=3.8.2
  - r-highr=0.9
  - r-hms=1.1.0
  - r-htmltools=0.5.1.1
  - r-httr=1.4.2
  - r-igraph=1.2.6
  - r-isoband=0.2.4
  - r-jsonlite=1.7.2
  - r-kernsmooth=2.23_20
  - r-knitr=1.33
  - r-labeling=0.4.2
  - r-lambda.r=1.2.4
  - r-languageserver=0.3.10
  - r-lattice=0.20_44
  - r-lazyeval=0.2.2
  - r-lifecycle=1.0.0
  - r-lintr=2.0.1
  - r-locfit=1.5_9.4
  - r-magrittr=2.0.1
  - r-markdown=1.1
  - r-mass=7.3_54
  - r-matrix=1.3_3
  - r-matrixstats=0.58.0
  - r-memoise=2.0.0
  - r-mgcv=1.8_35
  - r-mime=0.10
  - r-munsell=0.5.0
  - r-nlme=3.1_152
  - r-nnet=7.3_16
  - r-openssl=1.4.4
  - r-pillar=1.6.1
  - r-pkgconfig=2.0.3
  - r-pkgload=1.2.1
  - r-plogr=0.2.0
  - r-plotrix=3.8_1
  - r-plyr=1.8.6
  - r-polyclip=1.10_0
  - r-praise=1.0.0
  - r-prettyunits=1.1.1
  - r-processx=3.5.2
  - r-progress=1.2.2
  - r-ps=1.6.0
  - r-purrr=0.3.4
  - r-r.cache=0.15.0
  - r-r.methodss3=1.8.1
  - r-r.oo=1.24.0
  - r-r.utils=2.10.1
  - r-r6=2.5.0
  - r-rappdirs=0.3.3
  - r-rcolorbrewer=1.1_2
  - r-rcpp=1.0.6
  - r-rcpparmadillo=0.10.4.0.0
  - r-rcppeigen=0.3.3.9.1
  - r-rcurl=1.98_1.3
  - r-recommended=4.0
  - r-rematch2=2.1.2
  - r-remotes=2.3.0
  - r-repr=1.1.3
  - r-reshape2=1.4.4
  - r-rex=1.2.0
  - r-rlang=0.4.11
  - r-roxygen2=7.1.1
  - r-rpart=4.1_15
  - r-rprojroot=2.0.2
  - r-rsqlite=2.2.5
  - r-rstudioapi=0.13
  - r-rvcheck=0.1.8
  - r-scales=1.1.1
  - r-scatterpie=0.1.6
  - r-shadowtext=0.0.8
  - r-snow=0.4_3
  - r-spatial=7.3_14
  - r-stringdist=0.9.6.3
  - r-stringi=1.6.2
  - r-stringr=1.4.0
  - r-styler=1.4.1
  - r-survival=3.2_11
  - r-sys=3.4
  - r-testthat=3.0.2
  - r-tibble=3.1.2
  - r-tidygraph=1.2.0
  - r-tidyr=1.1.3
  - r-tidyselect=1.1.1
  - r-tweenr=1.0.2
  - r-utf8=1.2.1
  - r-vctrs=0.3.8
  - r-viridis=0.6.1
  - r-viridislite=0.4.0
  - r-waldo=0.2.5
  - r-withr=2.4.2
  - r-xfun=0.23
  - r-xml=3.99_0.6
  - r-xml2=1.3.2
  - r-xmlparsedata=1.0.5
  - r-xtable=1.8_4
  - r-yaml=2.2.1
  - r-zeallot=0.1.0
  - radian=0.5.10
  - ratelimiter=1.2.0
  - rchitect=0.3.30
  - readline=8.1
  - requests=2.25.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - s3transfer=0.4.2
  - samblaster=0.1.26
  - samtools=1.12
  - sed=4.8
  - setuptools=52.0.0
  - simplejson=3.17.2
  - six=1.16.0
  - slacker=0.14.0
  - smart_open=5.0.0
  - smmap=3.0.5
  - snakemake=6.4.0
  - snakemake-minimal=6.4.0
  - sqlite=3.35.5
  - stopit=1.1.2
  - sysroot_linux-64=2.12
  - tk=8.6.10
  - tktable=2.10
  - toml=0.10.2
  - toposort=1.6
  - traitlets=5.0.5
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - tzdata=2021a
  - ubiquerg=0.6.1
  - ucsc-bedclip=377
  - ucsc-bedgraphtobigwig=377
  - ucsc-bedsort=377
  - uritemplate=3.0.1
  - urllib3=1.26.4
  - veracitools=0.1.3
  - wcwidth=0.2.5
  - wheel=0.36.2
  - wrapt=1.12.1
  - xmlrunner=1.7.7
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.1
  - xorg-libxau=1.0.9
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.2.1
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.5.1
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.5.0
